### ISSUE TITLE
Multiple Principle isoforms from ensemble ESNT

### ISSUE THREAD

**Issue by ryandikdan** [appris/appris#21]
I've been trying to use your wonderful tool to select representative isoforms for FISH, but I've noticed that many Principle 1 isoforms for genes have multiple ENST IDs listed. When I look in ensemble there appears to be a primary transcript via MANE or another identifier, but shouldn't APPRIS identify only 1 isoform for each? For example, RCAN3, which lists both ENST00000374395 and ENST00000538532 as Principle 1, but on the ensemble website it lists them as having different CCDS (CCDS254 and CCDS57981), whereas in the APPRIS list they both have the same CCDS of CCDS254. It appears that when I go to the CCDS website then that your APPRIS listing is correct in this case, and perhaps it's an error on the ensemble site? 

I'm aware that appris focuses on protein sequence as opposed to RNA sequence of sliceoforms. Is there any tool that you are aware of that lists the primary isoforms of RNA focusing on sequencing? Thank you.

**Comment by appris** [comment]
Hello Ryan,

The reason APPRIS reports one or more isoforms is because some transcripts translate to the same protein isoform. In the example _RCAN3_, the transcripts IDs ENST00000374395 and ENST00000538532 translate to the same protein.

About the CCDS in Ensembl, I am sorry but I have seen the same CCDS254 identifiers:

![image](https://user-images.githubusercontent.com/14290225/123609562-0b881780-d800-11eb-8777-2a00aeffe727.png)

That's, APPRIS works at protein level... The functional part of a gene.

Best Regards,
J

**Comment by ryandikdan** [comment]
I must have been mistaken, thanks for clearing this up! I've been using the ensembl primary transcripts and then when not available, the longest highest ranked APPRIS transcript. Thanks!
